### ISSUE TITLE
Egységtesztek készítése/kiegészítése (xUnit...)

### ISSUE THREAD

**Issue by bencenemeth** [BME-MIT-IET/NullPointerException-iet-2018#1]

**Comment by ze3cru** [comment]
-outlay modul lokális unitTest mappája megvan  
-CategoryDtoTest JUnitTestek
-ExpenseDtoTest TestCase

**Comment by ze3cru** [comment]
android studión belűl van test coverage is.

![image](https://user-images.githubusercontent.com/25797005/39255200-445a3aa2-48ac-11e8-9f5a-476355e2dc4d.png)

**Comment by bencenemeth** [comment]
Model osztályok tesztjei:
![image](https://user-images.githubusercontent.com/33261842/40357294-fdf3d13e-5dbb-11e8-8776-9bd508518dbe.png)

Kódlefedettsége:
![image](https://user-images.githubusercontent.com/33261842/40357332-22e9dfc4-5dbc-11e8-923c-fdd3f59af2c1.png)
