### ISSUE TITLE
CI beüzemelése, ha még nincs (Travis, AppVeyor...)

### ISSUE THREAD

**Issue by bencenemeth** [BME-MIT-IET/NullPointerException-iet-2018#3]

**Comment by festmeny** [comment]
Az egész struktúrát meg kellett változtatnom, mert az előző struktúrában elég sok scriptet kellett volna írni. Ezután kellett egy helyes travis.yml file. A travis ekkor se buildelt helyesen. Sok utánaolvasás után rájöttünk, hogy egy keystore-ra van szüksége. Viszont még ezzel se működött. Az utolsó lépés a build.gradle buildTypes részén belül egy release build megadása volt. Mostanra a travis fordít.
