### ISSUE TITLE
Teszt lefedettség

### ISSUE THREAD

**Issue by ze3cru** [BME-MIT-IET/NullPointerException-iet-2018#4]

**Comment by festmeny** [comment]
A Jacoco-s lefedettséget inkább hanyagoltuk. A Jacoco legjobb tudásunk szerint csak Android tesztet tud mérni, Unit tesztet nem. Ezért inkább az Android Studio beépített lefedettség vizsgálóját használtuk. Kezdetben nem volt teszt írva, így 0%-os lefedettségünk volt.
![image](https://user-images.githubusercontent.com/28867249/40065661-93db7058-5862-11e8-9639-36d709a1ac8a.png)

**Comment by bencenemeth** [comment]
Unit tesztek elkészítése utáni új mérés.
Az osztályok 17%, a teljes kód 32%-át fedték le a tesztek.
![33096388_1986437091397691_7237827137158250496_n](https://user-images.githubusercontent.com/33261842/40356646-fafe92ae-5db9-11e8-969e-5d6941e04f2d.png)
